// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All .tsx examples of void-ui documentation.
 */

export default {
  'form/radio/basic': async () => import(/* webpackChunkName: "examples-form_radio" */ '@docs/examples/form/radio/basic.tsx'),
  'form/radio/group': async () => import(/* webpackChunkName: "examples-form_radio" */ '@docs/examples/form/radio/group.tsx'),
  'general/button/overview': async () => import(/* webpackChunkName: "examples-general_button" */ '@docs/examples/general/button/overview.tsx'),
  'layout/card/basic': async () => import(/* webpackChunkName: "examples-layout_card" */ '@docs/examples/layout/card/basic.tsx'),
  'layout/tabs/basic': async () => import(/* webpackChunkName: "examples-layout_tabs" */ '@docs/examples/layout/tabs/basic.tsx'),
  'layout/tabs/bordered-raise': async () => import(/* webpackChunkName: "examples-layout_tabs" */ '@docs/examples/layout/tabs/bordered-raise.tsx'),
  'layout/tabs/label-extra-class': async () => import(/* webpackChunkName: "examples-layout_tabs" */ '@docs/examples/layout/tabs/label-extra-class.tsx'),
};
