// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command "yarn gen-files".

/**
 * All .tsx examples of void-ui documentation.
 */

export default {
  'general/button/overview': async () => import(/* webpackChunkName: "chunk-general_button" */ '@docs/examples/general/button/overview.tsx'),
};
