// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All .vue examples of void-ui documentation.
 */

export default {
  'color/tone/overview'                         : async () => import(/* webpackChunkName: "examples-color_tone" */ './color/tone/overview.vue'),
  'form/radio/basic'                            : async () => import(/* webpackChunkName: "examples-form_radio" */ './form/radio/basic.vue'),
  'form/radio/group'                            : async () => import(/* webpackChunkName: "examples-form_radio" */ './form/radio/group.vue'),
  'form/switch/basic'                           : async () => import(/* webpackChunkName: "examples-form_switch" */ './form/switch/basic.vue'),
  'general/button/overview'                     : async () => import(/* webpackChunkName: "examples-general_button" */ './general/button/overview.vue'),
  'layout/card/array'                           : async () => import(/* webpackChunkName: "examples-layout_card" */ './layout/card/array.vue'),
  'layout/card/basic'                           : async () => import(/* webpackChunkName: "examples-layout_card" */ './layout/card/basic.vue'),
  'layout/flexbox/basic'                        : async () => import(/* webpackChunkName: "examples-layout_flexbox" */ './layout/flexbox/basic.vue'),
  'layout/flexbox/gap'                          : async () => import(/* webpackChunkName: "examples-layout_flexbox" */ './layout/flexbox/gap.vue'),
  'layout/flexbox/tiles'                        : async () => import(/* webpackChunkName: "examples-layout_flexbox" */ './layout/flexbox/tiles.vue'),
  'layout/flow/basic'                           : async () => import(/* webpackChunkName: "examples-layout_flow" */ './layout/flow/basic.vue'),
  'layout/popover/basic'                        : async () => import(/* webpackChunkName: "examples-layout_popover" */ './layout/popover/basic.vue'),
  'layout/tabs/basic'                           : async () => import(/* webpackChunkName: "examples-layout_tabs" */ './layout/tabs/basic.vue'),
  'layout/tabs/bordered-raise'                  : async () => import(/* webpackChunkName: "examples-layout_tabs" */ './layout/tabs/bordered-raise.vue'),
  'layout/tabs/label-extra-class'               : async () => import(/* webpackChunkName: "examples-layout_tabs" */ './layout/tabs/label-extra-class.vue'),
};
