// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All .vue examples of void-ui documentation.
 */

export default {
  'form/radio/basic': async () => import(/* webpackChunkName: "examples-form_radio" */ '@docs/examples/form/radio/basic.vue'),
  'form/radio/group': async () => import(/* webpackChunkName: "examples-form_radio" */ '@docs/examples/form/radio/group.vue'),
  'general/button/overview': async () => import(/* webpackChunkName: "examples-general_button" */ '@docs/examples/general/button/overview.vue'),
};
