// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All examples source code of void-ui documentation.
 */

export default {
  'color/tone/overview': [ 'scss', 'tsx', 'vue' ],
  'form/radio/basic': [ 'tsx', 'vue' ],
  'form/radio/group': [ 'tsx', 'vue' ],
  'form/switch/basic': [ 'tsx', 'vue' ],
  'general/button/overview': [ 'tsx', 'vue' ],
  'layout/card/array': [ 'scss', 'tsx', 'vue' ],
  'layout/card/basic': [ 'tsx', 'vue' ],
  'layout/flexbox/basic': [ 'tsx', 'vue' ],
  'layout/flexbox/gap': [ 'tsx', 'vue' ],
  'layout/flexbox/tiles': [ 'tsx', 'vue' ],
  'layout/flow/basic': [ 'scss', 'tsx', 'vue' ],
  'layout/tabs/basic': [ 'tsx', 'vue' ],
  'layout/tabs/bordered-raise': [ 'tsx', 'vue' ],
  'layout/tabs/label-extra-class': [ 'scss', 'tsx', 'vue' ],
};
