# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

default: &default
  working_directory: ~/project/void-ui
  docker:
    - image: circleci/node:latest

require_frame: &require_frame
  requires:
    - frame

jobs:
  frame:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-void-ui-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-void-ui-{{ .Branch }}-
            - v1-void-ui-
      - run: yarn --network-timeout 600000
      - save_cache:
          paths:
            - node_modules/
            - ~/.cache
          key: v1-void-ui-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - add_ssh_keys:
          fingerprints:
            - 0e:fd:15:00:19:2d:f5:ec:1b:f2:3e:4b:01:59:ce:33
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - persist_to_workspace:
          root: ~/
          paths:
            - project/void-ui
            - .ssh
  
  build-docs:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn --cwd packages/docs build
      - run: yarn --cwd packages/docs gen-pages
      - run:
          name: deploy to github-pages
          working_directory: packages/docs/dist
          command: |
            git init
            git config user.email huijife@outlook.com
            git config user.name huijife-bot
            git remote add origin git@github.com:HuijiFE/void-ui.git
            git add .
            git commit -m "auto deploy"
            git branch gh-pages
            git checkout gh-pages
            git branch -D master
            git push origin gh-pages --force

workflows:
  version: 2
  workflow:
    jobs:
      - frame:
          filters:
            branches:
              only:
                - master
      - build-docs:
          requires:
            - frame
          filters:
            branches:
              only: master
