// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All articles
 */

import { RouteConfig } from 'vue-router';

 const articles: RouteConfig[] = [
  {
    path: 'basic/cep',
    name: 'CEP 命名约定',
    component: async () => import('./basic/cep.md'),
  },
  {
    path: 'basic/color',
    name: 'Color 颜色',
    component: async () => import('./basic/color.md'),
  },
  {
    path: 'basic/responsive',
    name: 'Responsive 响应式',
    component: async () => import('./basic/responsive.md'),
  },
  {
    path: 'basic/style',
    name: 'Style 样式',
    component: async () => import('./basic/style.md'),
  },
  {
    path: 'color/grade',
    name: '',
    component: async () => import('./color/grade.md'),
  },
  {
    path: 'color/theme',
    name: 'Theme 主题',
    component: async () => import('./color/theme.md'),
  },
  {
    path: 'color/tone',
    name: 'Tone 色调',
    component: async () => import('./color/tone.md'),
  },
  {
    path: 'form/radio',
    name: 'Radio 单选框',
    component: async () => import('./form/radio.md'),
  },
  {
    path: 'form/switch',
    name: 'Switch 开关',
    component: async () => import('./form/switch.md'),
  },
  {
    path: 'general/button',
    name: 'Button 按钮',
    component: async () => import('./general/button.md'),
  },
  {
    path: 'general/icon',
    name: 'Icon 图标',
    component: async () => import('./general/icon.md'),
  },
  {
    path: 'layout/card',
    name: 'Card 卡片',
    component: async () => import('./layout/card.md'),
  },
  {
    path: 'layout/flexbox',
    name: 'Flexbox 弹性盒子',
    component: async () => import('./layout/flexbox.md'),
  },
  {
    path: 'layout/flow',
    name: 'Flow 流式',
    component: async () => import('./layout/flow.md'),
  },
  {
    path: 'layout/popover',
    name: 'Popover 弹出框',
    component: async () => import('./layout/popover.md'),
  },
  {
    path: 'layout/tabs',
    name: 'Tabs 标签页',
    component: async () => import('./layout/tabs.md'),
  },
  {
    path: 'layout/uniform-scale',
    name: 'Uniform-Scale 等比缩放',
    component: async () => import('./layout/uniform-scale.md'),
  },
];

export default articles
