// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All .tsx examples of void-ui documentation.
 */

export default {
  'color/tone/overview'                         : async () => import(/* webpackChunkName: "examples-color_tone" */ './color/tone/overview'),
  'form/radio/basic'                            : async () => import(/* webpackChunkName: "examples-form_radio" */ './form/radio/basic'),
  'form/radio/group'                            : async () => import(/* webpackChunkName: "examples-form_radio" */ './form/radio/group'),
  'form/switch/basic'                           : async () => import(/* webpackChunkName: "examples-form_switch" */ './form/switch/basic'),
  'general/button/overview'                     : async () => import(/* webpackChunkName: "examples-general_button" */ './general/button/overview'),
  'layout/card/array'                           : async () => import(/* webpackChunkName: "examples-layout_card" */ './layout/card/array'),
  'layout/card/basic'                           : async () => import(/* webpackChunkName: "examples-layout_card" */ './layout/card/basic'),
  'layout/flexbox/basic'                        : async () => import(/* webpackChunkName: "examples-layout_flexbox" */ './layout/flexbox/basic'),
  'layout/flexbox/gap'                          : async () => import(/* webpackChunkName: "examples-layout_flexbox" */ './layout/flexbox/gap'),
  'layout/flexbox/tiles'                        : async () => import(/* webpackChunkName: "examples-layout_flexbox" */ './layout/flexbox/tiles'),
  'layout/flow/basic'                           : async () => import(/* webpackChunkName: "examples-layout_flow" */ './layout/flow/basic'),
  'layout/note/basic'                           : async () => import(/* webpackChunkName: "examples-layout_note" */ './layout/note/basic'),
  'layout/popover/basic'                        : async () => import(/* webpackChunkName: "examples-layout_popover" */ './layout/popover/basic'),
  'layout/tabs/basic'                           : async () => import(/* webpackChunkName: "examples-layout_tabs" */ './layout/tabs/basic'),
  'layout/tabs/bordered-raise'                  : async () => import(/* webpackChunkName: "examples-layout_tabs" */ './layout/tabs/bordered-raise'),
  'layout/tabs/label-extra-class'               : async () => import(/* webpackChunkName: "examples-layout_tabs" */ './layout/tabs/label-extra-class'),
  'layout/uniform-scale/basic'                  : async () => import(/* webpackChunkName: "examples-layout_uniform-scale" */ './layout/uniform-scale/basic'),
};
