// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All articles
 */

export default {
  'general/button': async () => import('@docs/articles/zh-CN/general/button.md'),
  'layout/flexbox': async () => import('@docs/articles/zh-CN/layout/flexbox.md'),
  'layout/flow': async () => import('@docs/articles/zh-CN/layout/flow.md'),
  'layout/tabs': async () => import('@docs/articles/zh-CN/layout/tabs.md'),
};
