// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All articles
 */

export default [
  {
    path: 'general/button',
    name: 'Button 按钮',
    component: async () => import('@docs/articles/zh-CN/general/button.md'),
  },
  {
    path: 'layout/flexbox',
    name: 'Flexbox 弹性盒子',
    component: async () => import('@docs/articles/zh-CN/layout/flexbox.md'),
  },
  {
    path: 'layout/flow',
    name: 'Flow 流式',
    component: async () => import('@docs/articles/zh-CN/layout/flow.md'),
  },
  {
    path: 'layout/tabs',
    name: 'Tabs 标签页',
    component: async () => import('@docs/articles/zh-CN/layout/tabs.md'),
  },
];
