// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All articles
 */

export default [
  {
    path: 'basic/cep',
    name: 'CEP 命名约定',
    component: async () => import('@docs/articles/zh-CN/basic/cep.md'),
  },
  {
    path: 'basic/color',
    name: 'Color 颜色',
    component: async () => import('@docs/articles/zh-CN/basic/color.md'),
  },
  {
    path: 'basic/responsive',
    name: 'Responsive 响应式',
    component: async () => import('@docs/articles/zh-CN/basic/responsive.md'),
  },
  {
    path: 'basic/style',
    name: 'Style 样式',
    component: async () => import('@docs/articles/zh-CN/basic/style.md'),
  },
  {
    path: 'form/radio',
    name: 'Radio 单选框',
    component: async () => import('@docs/articles/zh-CN/form/radio.md'),
  },
  {
    path: 'form/switch',
    name: 'Switch 开关',
    component: async () => import('@docs/articles/zh-CN/form/switch.md'),
  },
  {
    path: 'general/button',
    name: 'Button 按钮',
    component: async () => import('@docs/articles/zh-CN/general/button.md'),
  },
  {
    path: 'general/icon',
    name: 'Icon 图标',
    component: async () => import('@docs/articles/zh-CN/general/icon.md'),
  },
  {
    path: 'layout/card',
    name: 'Card 卡片',
    component: async () => import('@docs/articles/zh-CN/layout/card.md'),
  },
  {
    path: 'layout/flexbox',
    name: 'Flexbox 弹性盒子',
    component: async () => import('@docs/articles/zh-CN/layout/flexbox.md'),
  },
  {
    path: 'layout/flow',
    name: 'Flow 流式',
    component: async () => import('@docs/articles/zh-CN/layout/flow.md'),
  },
  {
    path: 'layout/tabs',
    name: 'Tabs 标签页',
    component: async () => import('@docs/articles/zh-CN/layout/tabs.md'),
  },
];
