// Do not edit this file.
// It is auto generated by script "scripts/gen-files.ts".
// To update this file, please run command `yarn gen-files`.
// tslint:disable

/**
 * All articles
 */

export default {
  'general/button': 'Button 按钮',
  'layout/flexbox': 'Flexbox Layout 弹性盒子布局',
  'layout/flow': 'Flow Layout 流式布局',
  'layout/tabs': 'Tabs 标签页',
};
