// This file is automatically generated by script "auto/controls", do not edit.

export { default as VdButton } from 'src/controls/button/VdButton.vue';
export { default as VdButtonGroup } from 'src/controls/button/VdButtonGroup.vue';
export { default as VdFlexbox } from 'src/controls/flexbox/VdFlexbox.vue';
export { default as VdRadio } from 'src/controls/radio/VdRadio.vue';
export { default as VdScore } from 'src/controls/score/VdScore.vue';
export { default as VdToggle } from 'src/controls/toggle/VdToggle.vue';
